CREATE TABLE IF NOT EXISTS INFORMACION_USUARIOS(
    CORREO VARCHAR(200) NOT NULL PRIMARY KEY,
    NOMBRE TEXT NOT NULL,
    TELEFONO VARCHAR(12),
    FECHA_CREACION TEXT,
    FOREIGN KEY (CORREO) REFERENCES USUARIOS (CORREO) ON DELETE CASCADE ON UPDATE CASCADE
);