CREATE TABLE IF NOT EXISTS NIVEL(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE TEXT NOT NULL,
    FECHA_CREACION TEXT NOT NULL,
    DATALEVEL LONGTEXT,
    CORREO VARCHAR(200) NOT NULL,
    FOREIGN KEY (CORREO) REFERENCES USUARIOS (CORREO) ON DELETE CASCADE ON UPDATE CASCADE
);